// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA8aH96YvULTTmDu3g9wB02ReQTZ4BC_wA',
    appId: '1:1066532627208:web:31c160e4fe5b27982c02bd',
    messagingSenderId: '1066532627208',
    projectId: 'outfithub',
    authDomain: 'outfithub.firebaseapp.com',
    storageBucket: 'outfithub.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCDGpjN__9WoSMeV8dRGFqqEsjJTuX93HI',
    appId: '1:1066532627208:android:44219637189ac8192c02bd',
    messagingSenderId: '1066532627208',
    projectId: 'outfithub',
    storageBucket: 'outfithub.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCiEbf_pNoZQIZSkcSgukPeb8Fob_J1rPU',
    appId: '1:1066532627208:ios:89b28d30abe352b72c02bd',
    messagingSenderId: '1066532627208',
    projectId: 'outfithub',
    storageBucket: 'outfithub.firebasestorage.app',
    iosBundleId: 'com.example.outfithub',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCiEbf_pNoZQIZSkcSgukPeb8Fob_J1rPU',
    appId: '1:1066532627208:ios:89b28d30abe352b72c02bd',
    messagingSenderId: '1066532627208',
    projectId: 'outfithub',
    storageBucket: 'outfithub.firebasestorage.app',
    iosBundleId: 'com.example.outfithub',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA8aH96YvULTTmDu3g9wB02ReQTZ4BC_wA',
    appId: '1:1066532627208:web:c26326ce6b4eed682c02bd',
    messagingSenderId: '1066532627208',
    projectId: 'outfithub',
    authDomain: 'outfithub.firebaseapp.com',
    storageBucket: 'outfithub.firebasestorage.app',
  );
}
